# .readthedocs.yaml
version: 2

# The default configuration for the build process
build:
  os: ubuntu-24.04  # Specify Windows as the build OS
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt


# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx conf.py file
